######### AUTOSTART #########

## BACKGROUND APPLICATIONS
# screen lock - auto lock after 7 min
###exec --no-startup-id "xautolock -detectsleep -time 5 -locker 'loginctl lock-session' -notify 60 -notifier 'notify-send -t 10000 -u low -e \"LOCKING screen in 1 min\"' -corners ----"
# auto hybernate
# exec --no-startup-id "xautolock -detectsleep -time 15 -locker 'loginctl lock-session && systemctl hibernate' -notify 60 -notifier 'notify-send -t 10000 -u low -e \"Hibernate in 1 min\"' -corners ----"
# set wallpaper and theme
exec --no-startup-id "wpg -s $(wpg -c)"
# authentication agent
exec --no-startup-id lxpolkit
# autostart non GUI scripts
exec_always --no-startup-id "~/.config/i3/autostart.py"
# GTK styling using lxsession
exec --no-startup-id lxsession -a -n
# compositor
exec --no-startup-id picom

# set monitor layout
exec_always --no-startup-id "autorandr --change"
# set docked state
# exec --no-startup-id dockd --daemon

# notifications
#exec --no-startup-id "~/.config/i3/keep_up_dunst.py"


## MINIMIZED APPLICATIONS
# password manager
exec --no-startup-id keepassxc
# KDE Connect
exec --no-startup-id kdeconnect-indicator
# manage network connections
exec --no-startup-id nm-applet
# red/night mode
# exec --no-startup-id redshift-gtk
# input method framework
#exec --no-startup-id "fcitx5 >> ~/fcitx5.log 2>&1"
#exec --no-startup-id ibus-daemon -rxRd

# JDownloader
# exec --no-startup-id JDownloader
# Discord
# exec --no-startup-id gtk-launch com.discordapp.Discord
# Whatsapp
# exec --no-startup-id whatsapp-for-linux
# Screenshots
# exec --no-startup-id flameshot
# Clipboardmanager # We use lxsession for now
# exec --no-startup-id copyq


## FOREGROUND APPLICATIONS
# email, calender, contacts, tasks
exec --no-startup-id sleep 20 && evolution -c mail
# browser
# exec --no-startup-id firefox
# XMPP messenger
# exec --no-startup-id dino
# music streaming
# exec --no-startup-id spotify

# check for updates
exec --no-startup-id sleep 20 && ~/.config/i3/check_updates.sh
# nextcloud
exec --no-startup-id nextcloud
