######## AUTO ASSIGN ########

# xprop | grep WM_CLASS
# first part of the WM_CLASS is the instance, the second part is the class
# native wayland apps use only app_id
# swaymsg -t get_tree | grep -e name -e app_id

# Example assignment
# assign [class="firefox|chromium"]          number 2
# assign [instance="code-oss|vscodium"]         number 5
# assign [class="mpv|vlc"]                   number 6
# 
# assign [class="TeamSpeak 3"]                number 8
# assign [instance="dino|discord|element|gajim|signal|telegram-desktop"]    number 8
# assign [instance="evolution" title="(?<!(K|C)alend(e|a)r)(.+Evolution)?"]    number 9

# for_window [instance="spotify"] move to workspace               number 10
# dropdown terminal: set size, position, move to scratchpad
# https://www.reddit.com/r/swaywm/comments/goxxzz/comment/io427vz/?context=3
for_window [title="^terminal-dropdown$"] floating enable, resize set 90ppt 42ppt, move position center, move up 28ppt, move scratchpad, scratchpad show




######### FLOATING #########
for_window [window_role="pop-up"]   floating enable, move absolute center
for_window [instance = "blueberry.py|discord-overlay|gnome-calendar|gnome-calculator|kdeconnect-app|pavucontrol|rofi"]  floating enable
for_window [class="de-rub-dez6a3-cardcertificatemanager-Main|sun-awt-X11-XFramePeer"]   floating enable
for_window [instance = "gnome-control-center"]  floating enable, resize set 60ppt, move position center
for_window [title = "htop-floating"]            floating enable, resize set 70ppt 70ppt, move position center
# evolution calendar
# for_window [title="(K|C)alend(e|a)r(.+Evolution)?"]   floating enable, resize set 70ppt 70ppt, move position center
