############ BAR ############

bar {
    tray_output primary
    # When strip_workspace_numbers is set to yes, any workspace that has a name of the form "[n][:][NAME]" will display only the name.
    strip_workspace_numbers no 
    # awesome5 font (see i3status-rust config) and font with powerline symbols
    font pango:$fontmono, $fontawesome 12
    id bar-0
    position top
    status_command "i3status-rs ~/.config/i3status-rust/config.toml"
    colors {
        #text
        separator $color0

        #backround of bar
        background $color0

                          #border,   backround,text
        focused_workspace  $coloract $coloract $color15
        active_workspace   $colorin  $colorin  $color15
        inactive_workspace $color0   $color8   $color15
        urgent_workspace   $coloru   $coloru   $color15
    }
}

# bar {
#     workspace_buttons no
#     mode hide
#     modifier none
#     # awesome5 font (see i3status-rust config) and font with powerline symbolsworkspace_buttons no
#     font pango:$fontmono, $fontawesome 12
#     id bar-1
#     position bottom
#     status_command "i3status-rs ~/.config/i3status-rust/config_infos.toml"
#     colors {
#         #text
#         separator $color0
# 
#         #backround of bar
#         background $color0
# 
#                           #border,   backround,text
#         focused_workspace  $coloract $coloract $color15
#         active_workspace   $colorin  $colorin  $color15
#         inactive_workspace $color0   $color8   $color15
#         urgent_workspace   $coloru   $coloru   $color15
#     }
# }