[settings]
set_wallpaper = true
gtk = true
active = 15
light_theme = false
editor = code
execute_cmd = false
backend = wal
alpha = 90
smart_sort = true
auto_adjust = false
vte = true
reload = true
command = 
keywords = default
terminal = true

