#!/usr/bin/env zsh

lock="Lock"
activate_auto_lock="Activate auto lock"
deactivate_auto_lock="Deactivate auto lock"
logout="Logout"
reboot="Reboot"
shutdown="Power off"
suspend="Suspend"
hibernate="Hibernate"
hibersus="Hibernate and suspend"

if [[ "$@" ]]; then
  locker=(loginctl lock-session)
  case "$@" in
  $lock | Lock) $locker ;;
  $activate_auto_lock) xautolock -enable ;;
  $deactivate_auto_lock) xautolock -disable ;;
  $logout) i3-msg exit ;;
  $reboot) reboot ;;
  $shutdown) poweroff ;;
  # $suspend)
  #   $locker
  #   systemctl suspend
  #   ;;
  $hibernate)
    $locker
    systemctl hibernate
    ;;
  # $hibersus)
  #   $lock
  #   systemctl hybrid-sleep
  #   ;;
  *) echo "what is that? -$@-" ;;
  esac
else
  echo -e "\
$lock\0icon\x1fsystem-lock-screen
$activate_auto_lock\0icon\x1flock
$deactivate_auto_lock\0icon\x1fobject-unlocked
$logout\0icon\x1fsystem-log-out
$reboot\0icon\x1fsystem-reboot
$shutdown\0icon\x1fsystem-shutdown
$hibernate\0icon\x1fsystem-suspend-hibernate"
# $suspend\0icon\x1fsystem-suspend
# $hibernate\0icon\x1fsystem-suspend-hibernate
# $hibersus\0icon\x1fsystem-suspend-hibernate"
fi
